export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_FAKULTETE_BEGIN = "GET_FAKULTETE_BEGIN";
export const GET_FAKULTETE_SUCCESS = "GET_FAKULTETE_SUCCESS";
export const GET_FAKULTETE_ERROR = "GET_FAKULTETE_ERROR";
