export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";



export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const GET_FAKULTETE_BEGIN = "GET_FAKULTETE_BEGIN";
export const GET_FAKULTETE_SUCCESS = "GET_FAKULTETE_SUCCESS";
export const GET_FAKULTETE_ERROR = "GET_FAKULTETE_ERROR";

export const SHTO_FAKULTET_BEGIN = "SHTO_FAKULTET_BEGIN";
export const SHTO_FAKULTET_SUCCESS = "SHTO_FAKULTET_SUCCESS";
export const SHTO_FAKULTET_ERROR = "SHTO_FAKULTET_ERROR";

export const FSHIJ_FAKULTET_BEGIN = "FSHIJ_FAKULTET_BEGIN";
export const FSHIJ_FAKULTET_SUCCESS = "FSHIJ_FAKULTET_SUCCESS";
export const FSHIJ_FAKULTET_ERROR = "FSHIJ_FAKULTET_ERROR";

export const PERDITESO_FAKULTET_BEGIN = "PERDITESO_FAKULTET_BEGIN";
export const PERDITESO_FAKULTET_SUCCESS = "PERDITESO_FAKULTET_SUCCESS";
export const PERDITESO_FAKULTET_ERROR = "PERDITESO_FAKULTET_ERROR";

export const SHTO_DEPARTAMENT_BEGIN = "SHTO_DEPARTAMENT_BEGIN";
export const SHTO_DEPARTAMENT_SUCCESS = "SHTO_DEPARTAMENT_SUCCESS";
export const SHTO_DEPARTAMENT_ERROR = "SHTO_DEPARTAMENT_ERROR";

export const FSHIJ_DEPARTAMENT_BEGIN = "FSHIJ_DEPARTAMENT_BEGIN";
export const FSHIJ_DEPARTAMENT_SUCCESS = "FSHIJ_DEPARTAMENT_SUCCESS";
export const FSHIJ_DEPARTAMENT_ERROR = "FSHIJ_DEPARTAMENT_ERROR";

export const PERDITESO_DEPARTAMENT_BEGIN = "PERDITESO_DEPARTAMENT_BEGIN";
export const PERDITESO_DEPARTAMENT_SUCCESS = "PERDITESO_DEPARTAMENT_SUCCESS";
export const PERDITESO_DEPARTAMENT_ERROR = "PERDITESO_DEPARTAMENT_ERROR";

export const GET_DEPARTAMENTE_BEGIN = "GET_DEPARTAMENTE_BEGIN";
export const GET_DEPARTAMENTE_SUCCESS = "GET_DEPARTAMENTE_SUCCESS";
export const GET_DEPARTAMENTE_ERROR = "GET_DEPARTAMENTE_ERROR";